"""Data Explorer — read-only SQL console over data/pm_pnl.db."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import streamlit as st

from app.components.controls import render_date_filter
from app.components.theme import page_header, section, setup_page
from src.config import DB_PATH
from src.db import list_tables, query, table_schema

setup_page("Data Explorer", "🗄️")
page_header(
    "Data Explorer",
    "Query the SQLite database directly. "
    "All data is stored in data/pm_pnl.db and regenerated by `python run.py`.",
)

if not DB_PATH.exists():
    st.error("Database not found. Run `python run.py` to generate it.")
    st.stop()

bounds = query("SELECT MIN(date) as lo, MAX(date) as hi FROM eod_prices").iloc[0]
render_date_filter(bounds["lo"], bounds["hi"])

# ---- Schema browser ----------------------------------------------------------
section("Database Schema")

tables_and_views = list_tables()
tables = [(n, t) for n, t in tables_and_views if t == "table"]
views  = [(n, t) for n, t in tables_and_views if t == "view"]

col1, col2 = st.columns(2)
with col1:
    st.markdown("**Tables**")
    for name, _ in tables:
        with st.expander(name):
            cols = table_schema(name)
            col_df_data = [{"Column": r[1], "Type": r[2], "Not Null": bool(r[3]), "PK": bool(r[5])} for r in cols]
            import pandas as pd
            st.dataframe(pd.DataFrame(col_df_data), hide_index=True, use_container_width=True)

with col2:
    st.markdown("**Views** (SQL joins, no data duplication)")
    for name, _ in views:
        with st.expander(name):
            cols = table_schema(name)
            col_df_data = [{"Column": r[1], "Type": r[2]} for r in cols]
            st.dataframe(pd.DataFrame(col_df_data), hide_index=True, use_container_width=True)

# ---- Example queries ---------------------------------------------------------
section("Example Queries")

EXAMPLES = {
    "PM hierarchy (roster with pod & team)": "SELECT * FROM vw_manager_hierarchy ORDER BY pm_id;",
    "Top 10 positions by NMV (latest date)": (
        "SELECT pv.pm_id, pv.ticker, pv.quantity, pv.close_price, pv.nmv\n"
        "FROM vw_mtm_positions pv\n"
        "WHERE pv.date = (SELECT MAX(date) FROM eod_prices)\n"
        "ORDER BY ABS(pv.nmv) DESC\n"
        "LIMIT 10;"
    ),
    "Daily trade count by PM": (
        "SELECT pm_id, date, COUNT(*) AS trades, SUM(trade_notional) AS total_notional\n"
        "FROM trade_blotter\n"
        "GROUP BY pm_id, date\n"
        "ORDER BY date DESC\n"
        "LIMIT 20;"
    ),
    "Price history for one instrument": (
        "SELECT date, close_price FROM eod_prices\n"
        "WHERE ticker = (SELECT ticker FROM security_master LIMIT 1)\n"
        "ORDER BY date;"
    ),
    "Instrument count by asset class": (
        "SELECT asset_class, COUNT(*) AS n_instruments\n"
        "FROM security_master\n"
        "GROUP BY asset_class\n"
        "ORDER BY n_instruments DESC;"
    ),
    "BUY vs SELL volume by PM": (
        "SELECT pm_id, side, COUNT(*) AS trade_count, SUM(trade_notional) AS total_notional\n"
        "FROM trade_blotter\n"
        "GROUP BY pm_id, side\n"
        "ORDER BY pm_id, side;"
    ),
}

chosen = st.selectbox("Load an example query", ["(type your own)"] + list(EXAMPLES.keys()))
default_sql = EXAMPLES.get(chosen, "SELECT * FROM vw_manager_hierarchy LIMIT 20;")

# ---- SQL console -------------------------------------------------------------
section("Run SQL")

sql_input = st.text_area(
    "SELECT query (read-only — non-SELECT statements are blocked)",
    value=default_sql,
    height=140,
    key="sql_console",
)

if st.button("Run Query", type="primary"):
    sql = sql_input.strip()
    if not sql.upper().startswith("SELECT"):
        st.error("Only SELECT statements are allowed in the explorer.")
    else:
        try:
            result = query(sql)
            st.success(f"{len(result):,} row(s) returned.")
            st.dataframe(result, use_container_width=True, height=400)
        except Exception as exc:
            st.error(f"Query error: {exc}")

# ---- How to query outside the app -------------------------------------------
section("Query Outside the App")
st.markdown(
    """
**1. DB Browser for SQLite** (GUI, recommended for non-coders)
- Download free from [sqlitebrowser.org](https://sqlitebrowser.org)
- Open `data/pm_pnl.db` → click **Execute SQL** tab

**2. SQLite CLI**
```bash
sqlite3 data/pm_pnl.db
.tables
SELECT * FROM v_pm_roster;
.quit
```

**3. Python (pandas)**
```python
import sqlite3, pandas as pd
conn = sqlite3.connect("data/pm_pnl.db")
df = pd.read_sql("SELECT * FROM v_pm_roster", conn)
conn.close()
```

**4. VS Code extension** — install *SQLite Viewer*, open `data/pm_pnl.db` directly.

> The database is **not committed to git**. Run `python run.py` on a fresh clone to regenerate it.
"""
)
