"""SQLite data-access layer for pm_pnl.db.

Single source of truth for schema DDL, table writes, and reads.
The database is regenerated by `python run.py`; never committed to git.
"""
from __future__ import annotations

import sqlite3
from pathlib import Path
from typing import Any

import pandas as pd

from src.config import DB_PATH

_DDL = """
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS pods (
    pod_id          TEXT PRIMARY KEY,
    name            TEXT NOT NULL,
    strategy_type   TEXT,
    allocated_capital REAL
);

CREATE TABLE IF NOT EXISTS teams (
    team_id TEXT PRIMARY KEY,
    name    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS pms (
    pm_id             TEXT PRIMARY KEY,
    pod_id            TEXT NOT NULL REFERENCES pods(pod_id),
    team_id           TEXT NOT NULL REFERENCES teams(team_id),
    name              TEXT NOT NULL,
    allocated_capital REAL,
    payout_ratio      REAL,
    hurdle_rate       REAL,
    initial_HWM       REAL,
    skill             REAL,
    prior_year_pnl    REAL
);

CREATE TABLE IF NOT EXISTS instruments (
    ticker       TEXT PRIMARY KEY,
    asset_class  TEXT,
    sector       TEXT,
    strategy_tag TEXT,
    beta         REAL,
    alpha        REAL,
    idio_vol     REAL
);

CREATE TABLE IF NOT EXISTS prices (
    date   TEXT NOT NULL,
    ticker TEXT NOT NULL REFERENCES instruments(ticker),
    price  REAL NOT NULL,
    PRIMARY KEY (date, ticker)
);

CREATE TABLE IF NOT EXISTS positions (
    date   TEXT NOT NULL,
    pm_id  TEXT NOT NULL REFERENCES pms(pm_id),
    ticker TEXT NOT NULL REFERENCES instruments(ticker),
    qty    REAL NOT NULL,
    PRIMARY KEY (date, pm_id, ticker)
);

CREATE TABLE IF NOT EXISTS trades (
    trade_id   INTEGER PRIMARY KEY AUTOINCREMENT,
    date       TEXT    NOT NULL,
    pm_id      TEXT    NOT NULL REFERENCES pms(pm_id),
    ticker     TEXT    NOT NULL REFERENCES instruments(ticker),
    side       TEXT    NOT NULL,
    qty_change REAL    NOT NULL,
    price      REAL    NOT NULL,
    notional   REAL    NOT NULL
);

CREATE VIEW IF NOT EXISTS v_pm_roster AS
SELECT
    p.pm_id, p.name, p.allocated_capital, p.payout_ratio,
    p.hurdle_rate, p.initial_HWM, p.skill, p.prior_year_pnl,
    pod.pod_id, pod.name      AS pod_name, pod.strategy_type,
    t.team_id,  t.name        AS team_name
FROM pms p
JOIN pods  pod ON p.pod_id  = pod.pod_id
JOIN teams t   ON p.team_id = t.team_id;

CREATE VIEW IF NOT EXISTS v_position_value AS
SELECT
    pos.date, pos.pm_id, pos.ticker, pos.qty,
    pr.price,
    pos.qty * pr.price AS nmv
FROM positions pos
JOIN prices pr ON pos.date = pr.date AND pos.ticker = pr.ticker;
"""


def connect(path: str | Path = DB_PATH) -> sqlite3.Connection:
    """Return a connection with FK enforcement on."""
    conn = sqlite3.connect(str(path))
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def _derive_trades(positions: pd.DataFrame, prices: pd.DataFrame) -> pd.DataFrame:
    """Derive an OMS-style trade log from day-over-day qty changes."""
    pos = positions.sort_values(["pm_id", "ticker", "date"])
    pos["qty_prev"] = pos.groupby(["pm_id", "ticker"])["qty"].shift(1)
    changed = pos[pos["qty_prev"].notna() & (pos["qty"] != pos["qty_prev"])].copy()
    changed["qty_change"] = changed["qty"] - changed["qty_prev"]

    price_map = prices.set_index(["date", "ticker"])["price"]
    changed["price"] = changed.set_index(["date", "ticker"]).index.map(price_map)
    changed = changed.dropna(subset=["price"])

    changed["side"] = changed["qty_change"].apply(lambda x: "BUY" if x > 0 else "SELL")
    changed["notional"] = changed["qty_change"].abs() * changed["price"]
    return changed[["date", "pm_id", "ticker", "side", "qty_change", "price", "notional"]].reset_index(drop=True)


def write_database(
    tables: dict[str, pd.DataFrame],
    cfg: dict[str, Any],
    path: str | Path = DB_PATH,
) -> None:
    """Create schema and bulk-insert all tables + derived trades into the DB.

    Drops and recreates the file on each call so re-running run.py is idempotent.
    """
    db_path = Path(path)
    db_path.parent.mkdir(parents=True, exist_ok=True)
    if db_path.exists():
        db_path.unlink()

    conn = connect(db_path)
    # Create all tables and views via DDL.
    conn.executescript(_DDL)
    conn.commit()

    # Teams come from config (not generated as a DataFrame).
    teams_df = pd.DataFrame(cfg["teams"])[["team_id", "name"]]

    # Write tables in FK-dependency order.
    write_order = [
        ("pods",        tables["pods"]),
        ("teams",       teams_df),
        ("pms",         tables["pms"]),
        ("instruments", tables["instruments"]),
        ("prices",      tables["prices"]),
        ("positions",   tables["positions"]),
    ]
    for name, df in write_order:
        _write_table(conn, name, df)

    trades = _derive_trades(tables["positions"], tables["prices"])
    _write_table(conn, "trades", trades)

    conn.commit()
    conn.close()


def _write_table(conn: sqlite3.Connection, name: str, df: pd.DataFrame) -> None:
    """Write a DataFrame to a table, converting dates to ISO strings."""
    out = df.copy()
    for col in out.select_dtypes(include=["datetime64[ns]", "datetimetz"]).columns:
        out[col] = out[col].dt.strftime("%Y-%m-%d")
    out.to_sql(name, conn, if_exists="append", index=False)


def read_table(name: str, path: str | Path = DB_PATH) -> pd.DataFrame:
    """Read a full table or view into a DataFrame, parsing date columns."""
    conn = connect(path)
    df = pd.read_sql(f"SELECT * FROM {name}", conn, parse_dates=["date"])  # noqa: S608
    conn.close()
    return df


def query(sql: str, path: str | Path = DB_PATH) -> pd.DataFrame:
    """Run an arbitrary SELECT and return a DataFrame."""
    conn = connect(path)
    df = pd.read_sql(sql, conn, parse_dates=["date"])
    conn.close()
    return df


def list_tables(path: str | Path = DB_PATH) -> list[str]:
    """Return all user tables and views in the database."""
    conn = connect(path)
    rows = conn.execute(
        "SELECT name, type FROM sqlite_master WHERE type IN ('table','view') ORDER BY type, name"
    ).fetchall()
    conn.close()
    return [(r[0], r[1]) for r in rows]


def table_schema(name: str, path: str | Path = DB_PATH) -> list[tuple]:
    """Return column info for a table: (cid, name, type, notnull, default, pk)."""
    conn = connect(path)
    rows = conn.execute(f"PRAGMA table_info({name})").fetchall()  # noqa: S608
    conn.close()
    return rows
