"""SQLite data-access layer for pm_pnl.db.

Single source of truth for schema DDL, table writes, and reads.
The database is regenerated by `python run.py`; never committed to git.
"""
from __future__ import annotations

import sqlite3
from pathlib import Path
from typing import Any

import pandas as pd

from src.config import DB_PATH

_DDL = """
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS strategy_pods (
    pod_id        TEXT PRIMARY KEY,
    pod_name      TEXT NOT NULL,
    strategy_type TEXT,
    pod_aum       REAL
);

CREATE TABLE IF NOT EXISTS investment_teams (
    team_id   TEXT PRIMARY KEY,
    team_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS portfolio_managers (
    pm_id             TEXT PRIMARY KEY,
    pod_id            TEXT NOT NULL REFERENCES strategy_pods(pod_id),
    team_id           TEXT NOT NULL REFERENCES investment_teams(team_id),
    pm_name           TEXT NOT NULL,
    pm_aum            REAL,
    payout_ratio      REAL,
    hurdle_rate       REAL,
    initial_hwm       REAL,
    skill             REAL,
    loss_carryforward REAL,
    base_salary       REAL
    -- NOTE: ticker is used as PK in security_master (acceptable for MVP with
    -- synthetic, stable tickers). In production use ISIN/CUSIP + surrogate key.
);

CREATE TABLE IF NOT EXISTS security_master (
    ticker           TEXT PRIMARY KEY,
    asset_class      TEXT,
    sector           TEXT,
    strategy_tag     TEXT,
    beta             REAL,
    alpha            REAL,
    idiosyncratic_vol REAL
);

CREATE TABLE IF NOT EXISTS eod_prices (
    date        TEXT NOT NULL,
    ticker      TEXT NOT NULL REFERENCES security_master(ticker),
    close_price REAL NOT NULL,
    PRIMARY KEY (date, ticker)
);

CREATE TABLE IF NOT EXISTS eod_positions (
    date     TEXT NOT NULL,
    pm_id    TEXT NOT NULL REFERENCES portfolio_managers(pm_id),
    ticker   TEXT NOT NULL REFERENCES security_master(ticker),
    quantity REAL NOT NULL,
    PRIMARY KEY (date, pm_id, ticker)
);

CREATE TABLE IF NOT EXISTS eod_income (
    date     TEXT NOT NULL,
    pm_id    TEXT NOT NULL REFERENCES portfolio_managers(pm_id),
    category TEXT NOT NULL,
    amount   REAL NOT NULL,
    PRIMARY KEY (date, pm_id, category)
);

CREATE TABLE IF NOT EXISTS trade_blotter (
    trade_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    date            TEXT    NOT NULL,
    pm_id           TEXT    NOT NULL REFERENCES portfolio_managers(pm_id),
    ticker          TEXT    NOT NULL REFERENCES security_master(ticker),
    side            TEXT    NOT NULL,
    quantity_delta  REAL    NOT NULL,
    execution_price REAL    NOT NULL,
    trade_notional  REAL    NOT NULL
);

CREATE TABLE IF NOT EXISTS run_manifest (
    run_id       INTEGER PRIMARY KEY AUTOINCREMENT,
    run_at       TEXT    NOT NULL,
    git_ref      TEXT,
    n_prices     INTEGER,
    n_positions  INTEGER,
    n_income     INTEGER,
    recon_pass   INTEGER NOT NULL,
    n_checks     INTEGER,
    pipeline_sec REAL
);

CREATE VIEW IF NOT EXISTS vw_manager_hierarchy AS
SELECT
    p.pm_id, p.pm_name, p.pm_aum, p.payout_ratio,
    p.hurdle_rate, p.initial_hwm, p.skill, p.loss_carryforward,
    pod.pod_id,  pod.pod_name,  pod.strategy_type,
    t.team_id,   t.team_name
FROM portfolio_managers p
JOIN strategy_pods      pod ON p.pod_id  = pod.pod_id
JOIN investment_teams   t   ON p.team_id = t.team_id;

CREATE VIEW IF NOT EXISTS vw_mtm_positions AS
SELECT
    pos.date, pos.pm_id, pos.ticker, pos.quantity,
    pr.close_price,
    pos.quantity * pr.close_price AS nmv
FROM eod_positions pos
JOIN eod_prices pr ON pos.date = pr.date AND pos.ticker = pr.ticker;
"""


def ensure_schema(path: str | Path = DB_PATH) -> None:
    """Create tables/views that don't yet exist (idempotent; never drops data)."""
    conn = connect(path)
    try:
        conn.executescript(_DDL)
        conn.commit()
    finally:
        conn.close()


def write_manifest(row: dict, path: str | Path = DB_PATH) -> None:
    """Append one row to run_manifest (ensures schema exists first)."""
    ensure_schema(path)
    conn = connect(path)
    try:
        import pandas as _pd
        _pd.DataFrame([row]).to_sql("run_manifest", conn, if_exists="append", index=False)
        conn.commit()
    finally:
        conn.close()


def connect(path: str | Path = DB_PATH) -> sqlite3.Connection:
    """Return a connection with FK enforcement on."""
    conn = sqlite3.connect(str(path))
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def _derive_trades(positions: pd.DataFrame, prices: pd.DataFrame) -> pd.DataFrame:
    """Derive an OMS-style trade log from day-over-day quantity changes."""
    pos = positions.sort_values(["pm_id", "ticker", "date"])
    pos["_qty_prev"] = pos.groupby(["pm_id", "ticker"])["quantity"].shift(1)
    changed = pos[pos["_qty_prev"].notna() & (pos["quantity"] != pos["_qty_prev"])].copy()
    changed["quantity_delta"] = changed["quantity"] - changed["_qty_prev"]

    price_map = prices.set_index(["date", "ticker"])["close_price"]
    changed["execution_price"] = changed.set_index(["date", "ticker"]).index.map(price_map)
    changed = changed.dropna(subset=["execution_price"])

    changed["side"] = changed["quantity_delta"].apply(lambda x: "BUY" if x > 0 else "SELL")
    changed["trade_notional"] = changed["quantity_delta"].abs() * changed["execution_price"]
    return changed[
        ["date", "pm_id", "ticker", "side", "quantity_delta", "execution_price", "trade_notional"]
    ].reset_index(drop=True)


def write_database(
    tables: dict[str, pd.DataFrame],
    cfg: dict[str, Any],
    path: str | Path = DB_PATH,
) -> None:
    """Create schema and bulk-insert all tables + derived trades into the DB.

    Drops and recreates the file on each call so re-running run.py is idempotent.
    """
    db_path = Path(path)
    db_path.parent.mkdir(parents=True, exist_ok=True)
    if db_path.exists():
        db_path.unlink()

    conn = connect(db_path)
    try:
        conn.executescript(_DDL)
        conn.commit()

        # investment_teams comes from config; not a generated DataFrame.
        teams_df = pd.DataFrame(cfg["teams"]).rename(columns={"name": "team_name"})[
            ["team_id", "team_name"]
        ]

        write_order = [
            ("strategy_pods",       tables["strategy_pods"]),
            ("investment_teams",    teams_df),
            ("portfolio_managers",  tables["portfolio_managers"]),
            ("security_master",     tables["security_master"]),
            ("eod_prices",          tables["eod_prices"]),
            ("eod_positions",       tables["eod_positions"]),
            ("eod_income",          tables["eod_income"]),
        ]
        for tbl_name, df in write_order:
            _write_table(conn, tbl_name, df)

        trades = _derive_trades(tables["eod_positions"], tables["eod_prices"])
        _write_table(conn, "trade_blotter", trades)

        conn.commit()
    finally:
        conn.close()


def _write_table(conn: sqlite3.Connection, name: str, df: pd.DataFrame) -> None:
    """Write a DataFrame to a table, converting dates to ISO strings."""
    out = df.copy()
    for col in out.select_dtypes(include=["datetime64[ns]", "datetimetz"]).columns:
        out[col] = out[col].dt.strftime("%Y-%m-%d")
    out.to_sql(name, conn, if_exists="append", index=False)


def read_table(name: str, path: str | Path = DB_PATH) -> pd.DataFrame:
    """Read a full table or view into a DataFrame, parsing date columns."""
    conn = connect(path)
    df = pd.read_sql(f"SELECT * FROM {name}", conn, parse_dates=["date"])  # noqa: S608
    conn.close()
    return df


def query(sql: str, path: str | Path = DB_PATH) -> pd.DataFrame:
    """Run an arbitrary SELECT and return a DataFrame."""
    conn = connect(path)
    df = pd.read_sql(sql, conn, parse_dates=["date"])
    conn.close()
    return df


def list_tables(path: str | Path = DB_PATH) -> list[str]:
    """Return all user tables and views in the database."""
    conn = connect(path)
    rows = conn.execute(
        "SELECT name, type FROM sqlite_master WHERE type IN ('table','view') ORDER BY type, name"
    ).fetchall()
    conn.close()
    return [(r[0], r[1]) for r in rows]


def table_schema(name: str, path: str | Path = DB_PATH) -> list[tuple]:
    """Return column info for a table: (cid, name, type, notnull, default, pk)."""
    conn = connect(path)
    rows = conn.execute(f"PRAGMA table_info({name})").fetchall()  # noqa: S608
    conn.close()
    return rows
